/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Marco. Hernandez 9959-24-6201 
//Marco. Hernandez 9959-24-6291 24-04-2026  1. Creacion frmMantenimientoTransporte, implementaciones basicas


package Vista.Logistica;

/**
 *
 * @author macoh
 */
public class frmMantenimientoTransporte extends javax.swing.JInternalFrame {
  
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMantenimientoTransporte.class.getName());

    /**
     * Creates new form frmTransporrtes
     */
    public frmMantenimientoTransporte() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTransportes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cboxTipoBusqueda = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(782, 736));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(332, 239, 79, 31);

        tablaTransportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Empresa", "Tipo de Vehiculo"
            }
        ));
        tablaTransportes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaTransportesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tablaTransportes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(6, 288, 692, 406);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Transportes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(264, 23, 107, 25);

        cboxTipoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre", "Empresa", "Tipo Vehiculo" }));
        cboxTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(cboxTipoBusqueda);
        cboxTipoBusqueda.setBounds(32, 66, 124, 30);

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(32, 108, 145, 30);

        btnBuscar.setBackground(new java.awt.Color(255, 227, 250));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(209, 239, 76, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    //   limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cboxTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoBusquedaActionPerformed
        // TODO add your handling code here:

        // Oculta todos los campos de búsqueda al inicio
        // para evitar que aparezcan controles innecesarios
    /*    txtBuscar.setVisible(false);
        fechaInicio.setVisible(false);
        fechaFin.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        btnBuscar.setVisible(false);
*/
        // Obtiene el tipo de búsqueda seleccionado en el ComboBox
        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();

        // Dependiendo del tipo de búsqueda se muestran
        // los controles necesarios para ingresar los datos
       switch (seleccion) {
    case "ID":
        buscarPorID();
        break;
    case "Nombre":
        buscarPorNombre();
        break;
    case "Empresa":
        buscarPorEmpresa();
        break;
    case "Tipo de Vehículo":
        buscarPorTipo();
        break;
}
    }//GEN-LAST:event_cboxTipoBusquedaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      if (txtBuscar.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor para buscar", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String seleccion = cboxTipoBusqueda.getSelectedItem().toString();

        switch (seleccion) {
            case "ID":
                buscarPorID();
                break;
            case "Nombre":
                buscarPorNombre();
                break;
            case "Empresa":
                buscarPorEmpresa();
                break;
            case "Tipo de Vehículo":
                buscarPorTipo();
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un tipo de búsqueda");
        }
        //Registro de la accion en bitacora
   //     BitacoraDAO bitacoraDAO = new BitacoraDAO();
    //    bitacoraDAO.insert(idUsuario, Aplcodigo, "CONSULTA");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaTransportesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaTransportesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaTransportesAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMantenimientoTransporte().setVisible(true));
    }
    
    
    private void buscarPorID() {
        System.out.println("Buscando por ID...");
      
    }

    private void buscarPorNombre() {
        System.out.println("Buscando por Nombre...");
    }

    private void buscarPorEmpresa() {
        System.out.println("Buscando por Empresa...");
    }

    private void buscarPorTipo() {
        System.out.println("Buscando por Tipo de Vehículo...");
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboxTipoBusqueda;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaTransportes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
